name: fluro
description: >
  Fluro is a Flutter routing library that adds flexible routing options like wildcards, named
  parameters and clear route definitions.
version: 1.3.3
author: Yakka, LLC <flutter@theyakka.com>
homepage: https://github.com/theyakka/fluro

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ">=0.12.30+3 <0.13.0"

flutter:
  uses-material-design: false
